export const selectors = {
  SUBTEXT: '.subtext',
  BOARD: '.board',
  CLICK_COUNTER: '.click-counter',
  UNKNOWN_TILES: '.tile[data-type="unknown"]',
  TIMER: '.timer',
  BODY: '.body',
  HEADER: '.header',
  SCORE_SECTION: '.score-section',
  TABLE_BODY: '.table_body',
  CHANGE_THEME_BTN: '.change-theme-btn',
  GAME_SIZE_OPTIONS_TEXT: '.game-size-options-text',
  TITLE: '.title',
}

export const elements = {
  DIV: 'div',
  HEADER: 'header',
  H1: 'h1',
  BUTTON: 'button',
  MAIN: 'main',
  P: 'p',
  SELECT: 'select',
  OPTION: 'option',
  INPUT: 'input',
  THEAD: 'thead',
  TR: 'tr',
  TABLE: 'TABLE',
  TH: 'th',
  TBODY: 'tbody',
  TD: 'td',
}

export const classes = {
  TILE: 'tile',
  DEFAULT_CURSOR: 'default-cursor',
  ONE: 'one',
  TWO: 'two',
  THREE: 'three',
  FOUR: 'four',
  FIVE: 'five',
  SIX: 'six',
  SEVEN: 'seven',
  EIGHT: 'eight',
  HEADER: 'header',
  TITLE: 'title',
  NEW_GAME_BTN: 'new-game-btn',
  MAIN: 'main',
  TIMER: 'timer',
  CLICK_COUNTER: 'click-counter',
  BOARD_SECTION: 'board-section',
  SCORE_SECTION: 'score-section',
  SUBTEXT: 'subtext',
  BOARD: 'board',
  GAME_SIZE_OPTIONS: 'game-size-options',
  GAME_SIZE_OPTION: 'game-size-option',
  MINE_COUNT_SLIDER: 'mine-count-slider',
  CHANGE_THEME_BTN: 'change-theme-btn',
  COUNTER_WRAPPER: 'counter-wrapper',
  OPTIONS_WRAPPER: 'options-wrapper',
  GAME_SIZE_OPTIONS_TEXT: 'game-size-options-text',
  TABLE_BODY: 'table_body',
  RESULTS_TABLE: 'results-table',
  THEAD: 'thead',
  TH: 'th',
  TR: 'tr',
  TD: 'td',
  SIZE_WRAPPER: 'size-wrapper',
  BTN_WRAPPER: 'btn-wrapper',
  CHECK_RESULTS_BTN: 'check-results-btn',
}

export const tiles = {
  UNKNOWN: 'unknown',
  MINE: 'mine',
  NUMBER: 'number',
  RIGHT_CLICKED: 'right-clicked',
}

export const content = {
  EMPTY: '',
  QUESTION_MARK: '?',
  GAME_OVER_MESSAGE: 'Game over. Try again',
  CLICK_COUNTER: 'clicks: ',
  CLICK_COUNTER_INITIAL: 'clicks: 0',
  MINES_LEFT: 'Mines left: ',
  MINES_LEFT_INITIAL: 'Mines left: 10',
  WIN_MESSAGE: {
    FISRT_PART: 'Hooray! You found all mines in ',
    SECOND_PART: ' seconds and ',
    THIRD_PART: ' moves',
  },
  RESET_BTN_MESSAGE: 'Start over',
  TITLE: 'minesweeper',
  TIMER: 'time: ',
  TIMER_INITIAL: 'time: 0s',
  CHECK_RESULTS_BTN: 'results',
}

export const sizeProperty = '--size'

