import { Level } from './types';

export const levelsArray: Level[] = [
  {
    number: 1,
    task: 'Select the crabs',
    answers: ['crab'],
    tagsArray: [
      {
        name: 'crab',
        id: 1,
        idAttribute: null,
        strobe: true,
        child: null,
        imageClassname: 'crab',
      },
      {
        name: 'crab',
        id: 2,
        idAttribute: null,
        strobe: true,
        child: null,
        imageClassname: 'crab',
      }],
  },
  {
    number: 2,
    task: 'Select all the jellyfish',
    answers: ['jellyfish'],
    tagsArray: [
      {
        name: 'jellyfish',
        id: 1,
        idAttribute: null,
        strobe: true,
        child: null,
        imageClassname: 'jellyfish',
      },
      {
        name: 'crab',
        id: 2,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'crab',
      },
      {
        name: 'jellyfish',
        id: 3,
        idAttribute: null,
        strobe: true,
        child: null,
        imageClassname: 'jellyfish',
      },

    ],
  },
  {
    number: 3,
    task: 'Select the white jellyfish',
    answers: ['#jumping'],
    tagsArray: [
      {
        name: 'jellyfish',
        id: 1,
        idAttribute: 'white',
        strobe: true,
        child: null,
        imageClassname: 'jellyfish-white',

      },
      {
        name: 'jellyfish',
        id: 2,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'jellyfish',
      },
      {
        name: 'seal',
        id: 3,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'seal',
      },
    ],
  },
  {
    number: 4,
    task: 'Select the crab in the seaweed',
    answers: ['#blue'],
    tagsArray: [
      {
        name: 'seaweed',
        id: 1,
        idAttribute: null,
        strobe: false,
        imageClassname: 'seaweed',
        child: {
          name: 'crab',
          id: 4,
          idAttribute: null,
          strobe: true,
          child: null,
          imageClassname: 'crab',
        },
      },
      {
        name: 'crab',
        id: 2,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'crab',
      },
      {
        name: 'seal',
        id: 3,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'seal',
      },
    ],
  },

  {
    number: 5,
    task: 'Select the seahorse on the blue shell',
    answers: ['#blue'],
    tagsArray: [
      {
        name: 'seaweed',
        id: 1,
        idAttribute: null,
        strobe: false,
        imageClassname: 'seaweed',
        child: {
          name: 'crab',
          id: 2,
          idAttribute: null,
          strobe: false,
          child: null,
          imageClassname: 'crab',
        },
      },
      {
        name: 'shell',
        id: 3,
        idAttribute: null,
        strobe: false,
        imageClassname: 'shell',
        child: {
          name: 'seahorse',
          id: 4,
          idAttribute: null,
          strobe: false,
          child: null,
          imageClassname: 'seahorse',
        },
      },
      {
        name: 'shell',
        id: 5,
        idAttribute: 'blue',
        strobe: false,
        imageClassname: 'shell-blue',
        child: {
          name: 'seahorse',
          id: 6,
          idAttribute: null,
          strobe: true,
          child: null,
          imageClassname: 'seahorse',
        },
      },
    ],
  },

  {
    number: 6,
    task: 'Select the small octopuses',
    answers: ['#blue'],
    tagsArray: [
      {
        name: 'octopus',
        id: 1,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'octopus',
      },
      {
        name: 'octopus',
        id: 2,
        idAttribute: 'small',
        strobe: true,
        child: null,
        imageClassname: 'octopus-small',
      },
      {
        name: 'shell',
        id: 3,
        idAttribute: null,
        strobe: false,
        imageClassname: 'shell',
        child: {
          name: 'octopus',
          id: 4,
          idAttribute: 'small',
          strobe: true,
          child: null,
          imageClassname: 'octopus-small',
        },
      },
      {
        name: 'shell',
        id: 5,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'shell',
      },
    ],
  },


  {
    number: 7,
    task: 'Select the small crabs',
    answers: ['#blue'],
    tagsArray: [
      {
        name: 'octopus',
        id: 1,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'octopus',
      },
      {
        name: 'octopus',
        id: 2,
        idAttribute: 'small',
        strobe: true,
        child: null,
        imageClassname: 'octopus-small',
      },
      {
        name: 'shell',
        id: 3,
        idAttribute: null,
        strobe: false,
        imageClassname: 'shell',
        child: {
          name: 'crab',
          id: 4,
          idAttribute: 'small',
          strobe: true,
          child: null,
          imageClassname: 'crab-small',
        },
      },
      {
        name: 'seaweed',
        id: 5,
        idAttribute: null,
        strobe: false,
        imageClassname: 'seaweed',
        child: {
          name: 'crab',
          id: 6,
          idAttribute: null,
          strobe: true,
          child: null,
          imageClassname: 'crab-small',
        },
      },
    ],
  },


  {
    number: 8,
    task: 'Select the small crabs on the shells',
    answers: ['#blue'],
    tagsArray: [
      {
        name: 'octopus',
        id: 1,
        idAttribute: null,
        strobe: false,
        child: null,
        imageClassname: 'octopus',
      },
      {
        name: 'octopus',
        id: 2,
        idAttribute: 'small',
        strobe: true,
        child: null,
        imageClassname: 'octopus-small',
      },
      {
        name: 'shell',
        id: 3,
        idAttribute: null,
        strobe: false,
        imageClassname: 'shell',
        child: {
          name: 'crab',
          id: 4,
          idAttribute: 'small',
          strobe: true,
          child: null,
          imageClassname: 'crab-small',
        },
      },
      {
        name: 'seaweed',
        id: 5,
        idAttribute: null,
        strobe: false,
        imageClassname: 'seaweed',
        child: {
          name: 'crab',
          id: 6,
          idAttribute: null,
          strobe: true,
          child: null,
          imageClassname: 'crab-small',
        },
      },
    ],
  },
];
